packages:
  - ./hxt-charproperties
  - ./hxt-unicode
  - ./hxt-regex-xmlschema
  - ./hxt
  - ./hxt-curl
  - ./hxt-http
  - ./hxt-tagsoup
  - ./hxt-xpath
  - ./hxt-relaxng
  - ./hxt-xmlschema
  - ./hxt-xslt
  - ./hxt-cache

extra-deps: []

# lts with ghc-7.3
resolver: lts-6.10
